apiVersion: apps/v1
kind: Deployment
metadata:
  name: gestionformation
  labels:
    app: gestionformation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gestionformation
  template:
    metadata:
      labels:
        app: gestionformation
    spec:
      containers:
      - name: gestionformation
        image: souhakhelifi/gestionformation:latest
        ports:
        - containerPort: 8089
        env:
        - name: DB_HOST
          value: "localhost"
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          value: "user"
        - name: DB_USERNAME
          value: "root"
        - name: DB_PASSWORD
          value: ""
---
apiVersion: v1
kind: Service
metadata:
  name: gestionformation-service
spec:
  selector:
    app: gestionformation
  type: NodePort
  ports:
  - protocol: TCP
    port: 8089
    targetPort: 8089
    nodePort: 30089
