global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'exams-service'
    static_configs:
      - targets: ['exams-service:8082']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik-exams:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s
