apiVersion: apps/v1
kind: Deployment
metadata:
  name: exams-deployment
  namespace: skill2job
  labels:
    app: exams-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: exams-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: exams-service
    spec:
      containers:
        - name: exams-service
          image: klibimayssa/gestion-exams:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: exams-config
            - secretRef:
                name: exams-secret
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 90
            periodSeconds: 15
            failureThreshold: 3
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
