apiVersion: apps/v1
kind: Deployment
metadata:
  name: gestionformation
  labels:
    app: gestionformation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gestionformation
  template:
    metadata:
      labels:
        app: gestionformation
    spec:
      initContainers:
      - name: wait-for-mysql
        image: busybox
        command:
          - sh
          - -c
          - |
            echo "Waiting for MySQL to be ready..."
            until nc -z mysql-service 3306; do
              echo "MySQL not ready yet, retrying in 3s..."
              sleep 3
            done
            echo "MySQL is up! Starting app..."
            sleep 5
      containers:
      - name: gestionformation
        image: souhakhelifi/gestionformation:latest
        ports:
        - containerPort: 8083
        env:
        - name: DB_HOST
          value: "mysql-service"
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          value: "formation_db"
        - name: DB_USERNAME
          value: "root"
        - name: DB_PASSWORD
          value: "root"
        readinessProbe:
          tcpSocket:
            port: 8083
          initialDelaySeconds: 40
          periodSeconds: 10
          failureThreshold: 10
        livenessProbe:
          tcpSocket:
            port: 8083
          initialDelaySeconds: 90
          periodSeconds: 15
          failureThreshold: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: gestionformation-service
spec:
  selector:
    app: gestionformation
  type: NodePort
  ports:
  - protocol: TCP
    port: 8083
    targetPort: 8083
    nodePort: 30083
